export const styles = {
  container: {
    display: "flex",
    height: "100vh",
    width: { xs: "100%", sm: "100vw" },
    flexDirection: "column",
  },
  layoutContainer: {
    display: "flex",
    justifyContent: "space-between",
    flexDirection: "row",
    width: { xs: "100%", sm: "100vw" },
  },
  rightSideContainer: {
    display: "flex",
    flexDirection: "column",
    mb: { xs: 0, sm: "50px" },
    p: 5,
    backgroundColor: "#F4F4F9",
    height: "84vh",
  },
  leftSideContainer: {
    display: "flex",
    flexDirection: "column",
    mt: "20px",
    mr: { xs: 0, sm: "40px" },
    mb: { xs: "20px", sm: 0 },
    borderRadius: "10px",
    backgroundColor: "#F4F4F9",
    padding: { xs: "30px 20px 20px", sm: "24px 0 16px" },
  },
  formContainer: {
    display: "flex",
    justifyContent: "space-between",
    flexDirection: { xs: "column", md: "row" },
    padding: { sm: "8px" },
    paddingBottom: { sm: 0 },
    ml: { xs: 0, sm: "20px" },
  },
  boxesContainar: {
    display: "flex",
    flexDirection: "row",
    mt: { xs: 0, sm: "20px" },
    mr: { xs: 0, sm: "40px" },
    borderRadius: "10px",
    backgroundColor: "#F4F4F9",
    padding: {
      xs: "30px 20px 20px",
      sm: "20px 20px 20px 0",
      md: "30px 0 20px",
    },
  },
  policiesContainer: {
    display: "flex",
    flexDirection: "column",
    mt: "20px",
    mr: { xs: 0, sm: "40px" },
    mb: { xs: "20px", sm: 0 },
    alignItems: "center",
    borderRadius: "10px",
    backgroundColor: "#F4F4F9",
    padding: { xs: "30px 20px 20px", sm: "30px 0 20px" },
  },
  teamContainer: {
    display: "flex",
    flexDirection: "row",
    mr: { xs: 0, sm: "24px" },
    ml: "24px",
    mb: { xs: "20px", sm: 0 },
    borderRadius: "10px",
    backgroundColor: "#F4F4F9",
    padding: { xs: "30px 20px 20px", sm: "16px 0 0px" },
  },
  primaryText: {
    mb: "20px",
    textAlign: "center",
    fontWeight: "bold",
    fontSize: "24px",
    fontFamily: "Outfit",
    color: "#252525",
  },
  secondaryText: {
    textAlign: "center",
    fontWeight: "normal",
    fontSize: "20px",
    fontFamily: "Outfit",
    color: "#252525",
  },
  companyText: {
    fontSize: "26px",
    fontFamily: "Outfit",
    fontStyle: "normal",
    fontWeight: "bold",
    lineHeight: "normal",
    color: "#252525",
    ml: "24px",
    mr: "620px",
    mb: "-30px",
  },
  companyTextTwo: {
    fontSize: "26px",
    fontFamily: "Outfit",
    fontStyle: "normal",
    fontWeight: "bold",
    lineHeight: "normal",
    color: "#252525",
    whiteSpace: "nowrap",
    ml: "24px",
    mb: "-30px",
  },
  addCoApplicationContainer: {
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "flex-end",
    paddingRight: "20px",
    paddingBottom: { xs: "10px", sm: 0 },
    backgroundColor: "yellow",
  },
  addRowContainer: {
    display: "flex",
    justifyContent: "flex-end",
    paddingRight: "20px",
    paddingBottom: { xs: "10px", sm: 0 },
  },
  uploadFileBox: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    border: 1,
    borderStyle: "dashed",
    borderColor: "gray",
    backgroundColor: "white",
    height: "42px",
    width: "95%",
    mt: "12px",
  },
  uploadButton: {
    borderRadius: "20px",
    textTransform: "none",
    height: "42px",
    width: "11%",
    mt: "24px",
  },
  successUploadText: {
    mt: "24px",
    textAlign: "center",
    fontWeight: "bold",
    fontSize: "20px",
    fontFamily: "Outfit",
    color: "#62D690",
  },
  clientLogo: {
    borderRadius: "50%",
    height: "120px",
    width: "120px",
    border: "1px solid #BABABA",
    fontSize: "65px",
  },
  clientContainer: {
    display: "flex",
    flexDirection: "row",
    mb: { xs: "20px", sm: 0 },
    borderRadius: "10px",
    padding: {
      xs: "30px 20px 20px",
      sm: "20px 20px 20px 0",
      md: "30px 0 20px",
    },
  },
  clientTexts: {
    display: "flex",
  },
  clientLayout: {
    display: "flex",
    flexDirection: "column",
    justifyContent: "space-between",
    mb: "24px",
    ml: "24px",
    mr: { xs: 0, sm: "24px" },
    flexGrow: 1,
  },
  input: {
    display: "none",
  },
  image: {
    height: "200px",
    width: "200px",
    alignSelf: "center",
  },
};
export default styles;
